### ISSUE TITLE
Design feedback

### ISSUE THREAD

**Issue by jbenet** [data-preservation-programs/fil-onboarding-report#15]
We should have a figma of the current design so we can leave feedback, and have candidate next versions

**Comment by APiligrim** [comment]
> We should have a figma of the current design so we can leave feedback, and have candidate next versions

@jbenet this is the figma link https://www.figma.com/file/z2b7a845v4KI5NsQPbyuGo/Filecoin-Dashboard?type=design&node-id=705%3A2&t=xSjhAxNrYXqYJvie-1 , I'll add Anjor's current version here as well for feedback.
